[package]
name = "wgslfmt"
version = "0.1.0"
edition = "2024"
description = "Tool to find and fix WGSL/WESL formatting issues"
readme = "README.md"
repository = "https://github.com/wgsl-analyzer/wgsl-analyzer"
license = "Apache-2.0 OR MIT"
# build = "build.rs"
categories = ["development-tools"]

[dependencies]
anyhow.workspace = true
lexopt = "0.3.1"
prettydiff = "0.9.0"
wgsl-formatter.workspace = true

[lints]
workspace = true
