[package]
name = "ide-db"
version = "0.0.0"
repository.workspace = true
description = "IDE Database of wgsl-analyzer"

authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
crossbeam-channel.workspace = true
tracing.workspace = true
fst.workspace = true
rustc-hash.workspace = true
either.workspace = true
itertools.workspace = true
indexmap.workspace = true
memchr.workspace = true
salsa.workspace = true
salsa-macros.workspace = true
triomphe.workspace = true
nohash-hasher.workspace = true
smol_str.workspace = true
stdx.workspace = true
smallvec.workspace = true

base-db.workspace = true
hir-def.workspace = true
hir-ty.workspace = true
syntax.workspace = true
rowan.workspace = true
vfs.workspace = true
line-index.workspace = true

[dev-dependencies]
expect-test = "1.5.1"

[lints]
workspace = true
