[package]
name = "ide-db"
version = "0.0.0"
repository.workspace = true
description = "IDE Database of wgsl-analyzer"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
crossbeam-channel = "0.5.15"
tracing = "0.1.41"
fst = { version = "0.4.7", default-features = false }
rustc-hash = "2.1.1"
either = "1.15.0"
itertools = "0.14.0"
indexmap = "2.12.0"
memchr = "2.7.6"
salsa = "0.17.0-pre.2"
triomphe = { version = "0.1.15", default-features = false, features = ["std"] }
nohash-hasher = "0.2.0"
smol_str = "0.3.4"
smallvec = { version = "1.15.1", features = [
  "const_new",
  "union",
  "const_generics",
] }

base-db.workspace = true
hir-def.workspace = true
hir-ty.workspace = true
syntax.workspace = true
rowan = "0.16.1"
vfs.workspace = true
line-index = "0.1.2"

[dev-dependencies]
expect-test = "1.5.1"

[lints]
workspace = true
