[package]
name = "project-model"
version = "0.0.0"
repository.workspace = true
description = "A representation for a WESL project for wgsl-analyzer."

edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[dependencies]
anyhow = "1.0.100"
wesl-metadata = "0.0.5"
rustc-hash = "2.1.1"
semver = "1.0.27"
serde_json = "1.0.145"
serde = "1.0.228"
tracing = "0.1.41"
triomphe = "0.1.15"
la-arena = "0.3.1"
itertools = "0.14.0"

# local deps
base-db.workspace = true
# intern .workspace = true
# span.workspace = true
paths.workspace = true
stdx.workspace = true
edition.workspace = true
toolchain.workspace = true

[dev-dependencies]
expect-test = "1.5.1"

[lints]
workspace = true
